### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by a101010** [blopa/top-down-react-phaser-game-template#7]
When I check this out and run npm install I get errors. The first error is for eslint, but removing all eslint entries from package.json doesn't seem to help. 

output of npm install:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: eslint-plugin-flowtype@8.0.3
npm ERR! Found: eslint@7.32.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^7.32.0" from the root project
npm ERR!   peer eslint@"^7.5.0 || ^8.0.0" from @babel/eslint-parser@7.17.0
npm ERR!   node_modules/@babel/eslint-parser
npm ERR!     dev @babel/eslint-parser@"^7.17.0" from the root project
npm ERR!     peer @babel/eslint-parser@">=7.11.0" from @babel/eslint-plugin@7.17.7
npm ERR!     node_modules/@babel/eslint-plugin
npm ERR!       dev @babel/eslint-plugin@"^7.17.7" from the root project
npm ERR!     1 more (eslint-template-visitor)
npm ERR!   34 more (@babel/eslint-plugin, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^8.1.0" from eslint-plugin-flowtype@8.0.3
npm ERR! node_modules/eslint-plugin-flowtype
npm ERR!   dev eslint-plugin-flowtype@"^8.0.3" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: eslint@8.29.0
npm ERR! node_modules/eslint
npm ERR!   peer eslint@"^8.1.0" from eslint-plugin-flowtype@8.0.3
npm ERR!   node_modules/eslint-plugin-flowtype
npm ERR!     dev eslint-plugin-flowtype@"^8.0.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by a101010** [comment]
Okay, here's what I had to do to get this running:

1. delete package-lock.json // it seemed to be causing conflicts
2. npm install --force // still couldn't resolve dependencies without this
3. export NODE_OPTIONS=--openssl-legacy-provider
4. remove the PUBLIC_URL=/ from the start script, since it causes an error. It's okay to run PUBLIC_URL=/ npm start though. (I assume the same would be true for the build script, have to remove CI=false.)

Not sure there is a smooth upgrade path to the latest react-scripts.

**Comment by a101010** [comment]
I'm guessing these are typical problems for create react apps?

**Comment by blopa** [comment]
I just pushed a change to `main` that should fix it. Cheers.

**Comment by wizard-waqas** [comment]
I installed some packages using homebrew and that fixed it for me:
`brew install pkg-config cairo pango libpng jpeg giflib librsvg`
